server:
  port: 8081
spring:
  application:
    name: mymall-eureka-server
eureka:
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
